### ISSUE TITLE
Pysimplegui material button theme

### ISSUE THREAD

**Issue by ssweber** [ill13/Notes#1]
Hello there!

Back in 2020 you posted an example of a material button theme for pysimplegui. Did you ever post the code for that anywhere?

Im working on a rad library that uses pysimplegui, and am interested in providing developers options for better looking buttons.

**Comment by ill13** [comment]
I'll have to dig for it, if the code is any where is on a local backup. and I could never get Win10 OS transparency to work, nor could I get anti-aliased drawing screen drawing to work [within the PSG graphics context] so custom controls were out of the picture. 

That said, it looks like PSG supports TK/TTK themes now, so that would likely be a better direction.

This is probably the most relevant chunk. Literally  just end running around PSG and re-styling things after creation.

```
def recolor_single_button(button,swap_to='BTN_PRIMARY'):
    button_name = button + 'custombutton.TButton'
    gui_style = sg.ttk.Style()
    gui_style.map(button_name, foreground=[('pressed', '#333'),('active', TEXT_COLOR),('disabled', '#bbb')])
    gui_style.configure(button_name, focuscolor = sg.theme_button_color ) # hide focus indicator by setting it to the background color
    gui_style.configure(button_name, relief='flat')
    gui_style.configure(button_name, borderwidth=0 ) 
    gui_style.configure(button_name, highlightthickness=0) 

```

**Comment by ssweber** [comment]
Thanks! I really appreciate you taking the time to reply!
